"""
iac_generator.py
Generates Terraform / Pulumi code from parsed intent + Jinja2 templates.
Security best practices are baked into every template.
"""
import os
import re
import json
import hashlib
from pathlib import Path
from dataclasses import dataclass, field
from typing import List, Optional
from jinja2 import Environment, FileSystemLoader, BaseLoader, select_autoescape

# ─── Security enforcement constants ──────────────────────────────────────────

FORBIDDEN_PATTERNS = [
    (r'ingress\s*\{[^}]*cidr_blocks\s*=\s*\["0\.0\.0\.0/0"\]', "CRITICAL", "Open CIDR 0.0.0.0/0 in ingress rule"),
    (r'encrypted\s*=\s*false',           "CRITICAL", "Encryption explicitly disabled"),
    (r'publicly_accessible\s*=\s*true',  "CRITICAL", "Resource is publicly accessible"),
    (r'(AKIA|ASIA)[A-Z0-9]{16}',         "CRITICAL", "AWS Access Key ID pattern detected in code"),
    (r'["\'](?=[^"\']{16,})[A-Za-z0-9+/]{40}["\']', "HIGH", "Possible secret key in code"),
    (r'password\s*=\s*["\'][^${\'"]{3,}', "HIGH",    "Hardcoded password detected"),
    (r'skip_final_snapshot\s*=\s*true',  "HIGH",     "DB final snapshot skipped"),
    (r'deletion_protection\s*=\s*false', "MEDIUM",   "Deletion protection disabled"),
]

# ─── Inline Terraform templates (no file I/O needed for demo) ────────────────

AWS_SECURE_VPC_TF = '''
# ════════════════════════════════════════════════════════════
# Generated by Local AI DevSecOps Agent
# Cloud: AWS  |  Tool: Terraform  |  Security Level: HIGH
# Compliance: {{ compliance | join(", ") }}
# ════════════════════════════════════════════════════════════

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = { source = "hashicorp/aws", version = "~> 5.0" }
  }
}

provider "aws" {
  region = "{{ region }}"
  # Credentials from environment variables — never hardcoded:
  # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
  default_tags {
    tags = {
      ManagedBy    = "devsecops-agent"
      Compliance   = "{{ compliance | join('+') }}"
      Environment  = "{{ env | default('production') }}"
    }
  }
}

# ── KMS key for encryption ────────────────────────────────
resource "aws_kms_key" "main" {
  description             = "{{ name }}-encryption-key"
  deletion_window_in_days = 30
  enable_key_rotation     = true   # CIS 2.8, NIST SC-12
}

resource "aws_kms_alias" "main" {
  name          = "alias/{{ name }}"
  target_key_id = aws_kms_key.main.key_id
}

# ── VPC ───────────────────────────────────────────────────
resource "aws_vpc" "main" {
  cidr_block           = "{{ cidr | default('10.0.0.0/16') }}"
  enable_dns_hostnames = true
  enable_dns_support   = true
  tags = { Name = "{{ name }}-vpc" }
}

# ── Private Subnets (no public IPs ever) ─────────────────
{% for i in range(az_count | default(2)) %}
resource "aws_subnet" "private_{{ i }}" {
  vpc_id                  = aws_vpc.main.id
  cidr_block              = cidrsubnet(aws_vpc.main.cidr_block, 8, {{ i }})
  availability_zone       = data.aws_availability_zones.available.names[{{ i }}]
  map_public_ip_on_launch = false   # NEVER assign public IPs
  tags = { Name = "{{ name }}-private-{{ i }}", Tier = "private" }
}
{% endfor %}

data "aws_availability_zones" "available" { state = "available" }

# ── Default SG — deny all (CIS 4.3) ──────────────────────
resource "aws_default_security_group" "deny_all" {
  vpc_id = aws_vpc.main.id
  # No ingress/egress = deny all traffic
  tags = { Name = "{{ name }}-default-deny" }
}

# ── Security Group for private instance ───────────────────
resource "aws_security_group" "private_instance" {
  name        = "{{ name }}-private-sg"
  description = "Private instance — no internet access"
  vpc_id      = aws_vpc.main.id

  # No inbound from internet
  # Internal VPC communication only
  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [aws_vpc.main.cidr_block]   # Internal only
    description = "SSH from VPC only"
  }

  egress {
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]   # HTTPS out for updates (restrict if needed)
    description = "HTTPS outbound for updates"
  }

  tags = { Name = "{{ name }}-private-sg" }
}

{% if instance_count | default(0) > 0 %}
# ── EC2 Instance (Private, Encrypted) ────────────────────
data "aws_ami" "amazon_linux" {
  most_recent = true
  owners      = ["amazon"]
  filter {
    name   = "name"
    values = ["al2023-ami-*-x86_64"]
  }
}

resource "aws_instance" "private" {
  count                  = {{ instance_count | default(1) }}
  ami                    = data.aws_ami.amazon_linux.id
  instance_type          = "{{ instance_type | default('t3.micro') }}"
  subnet_id              = aws_subnet.private_0.id
  vpc_security_group_ids = [aws_security_group.private_instance.id]
  iam_instance_profile   = aws_iam_instance_profile.ec2_profile.name

  # IMDSv2 enforced — prevents SSRF-based metadata theft (CIS 5.6)
  metadata_options {
    http_endpoint               = "enabled"
    http_tokens                 = "required"   # IMDSv2 required
    http_put_response_hop_limit = 1
  }

  # Encrypted root volume
  root_block_device {
    encrypted   = true
    kms_key_id  = aws_kms_key.main.arn
    volume_size = {{ volume_size | default(20) }}
    volume_type = "gp3"
    delete_on_termination = true
  }

  # No public IP
  associate_public_ip_address = false

  tags = {
    Name = "{{ name }}-private-instance-${count.index}"
  }
}

# ── IAM role for EC2 — least privilege ────────────────────
resource "aws_iam_role" "ec2_role" {
  name = "{{ name }}-ec2-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "ec2.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
}

# SSM for remote access without SSH keys
resource "aws_iam_role_policy_attachment" "ssm" {
  role       = aws_iam_role.ec2_role.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

resource "aws_iam_instance_profile" "ec2_profile" {
  name = "{{ name }}-ec2-profile"
  role = aws_iam_role.ec2_role.name
}
{% endif %}

# ── VPC Flow Logs (CIS 3.9, SOC2 CC7.2) ─────────────────
resource "aws_cloudwatch_log_group" "flow_logs" {
  name              = "/aws/vpc/{{ name }}/flow-logs"
  retention_in_days = 90
  kms_key_id        = aws_kms_key.main.arn
}

resource "aws_iam_role" "flow_log_role" {
  name = "{{ name }}-flow-log-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "vpc-flow-logs.amazonaws.com" }
      Action    = "sts:AssumeRole"
    }]
  })
}

resource "aws_iam_role_policy" "flow_log_policy" {
  name   = "{{ name }}-flow-log-policy"
  role   = aws_iam_role.flow_log_role.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents",
        "logs:DescribeLogGroups",
        "logs:DescribeLogStreams"
      ]
      Resource = ["${aws_cloudwatch_log_group.flow_logs.arn}:*"]
    }]
  })
}

resource "aws_flow_log" "main" {
  vpc_id          = aws_vpc.main.id
  traffic_type    = "ALL"
  iam_role_arn    = aws_iam_role.flow_log_role.arn
  log_destination = aws_cloudwatch_log_group.flow_logs.arn
}

# ── Outputs ───────────────────────────────────────────────
output "vpc_id"            { value = aws_vpc.main.id }
output "private_subnet_ids" {
  value = [{% for i in range(az_count | default(2)) %}aws_subnet.private_{{ i }}.id{% if not loop.last %}, {% endif %}{% endfor %}]
}
output "kms_key_arn"       { value = aws_kms_key.main.arn }
{% if instance_count | default(0) > 0 %}
output "instance_ids"      { value = aws_instance.private[*].id }
{% endif %}
'''

GCP_SECURE_VPC_TF = '''
# Generated by Local AI DevSecOps Agent — GCP Secure VPC
terraform {
  required_providers {
    google = { source = "hashicorp/google", version = "~> 5.0" }
  }
}

provider "google" {
  project = "{{ project_id }}"
  region  = "{{ region }}"
  # Credentials from GOOGLE_APPLICATION_CREDENTIALS env var
}

# ── VPC (custom mode — no auto-created subnets) ───────────
resource "google_compute_network" "vpc" {
  name                    = "{{ name }}-vpc"
  auto_create_subnetworks = false   # Custom subnets only
  routing_mode            = "REGIONAL"
  delete_default_routes_on_create = true   # Block internet by default
}

# ── Private Subnet ────────────────────────────────────────
resource "google_compute_subnetwork" "private" {
  name                     = "{{ name }}-private"
  ip_cidr_range            = "{{ cidr | default('10.0.1.0/24') }}"
  region                   = "{{ region }}"
  network                  = google_compute_network.vpc.id
  private_ip_google_access = true   # Reach Google APIs without internet

  log_config {
    aggregation_interval = "INTERVAL_5_SEC"
    flow_sampling        = 0.5
    metadata             = "INCLUDE_ALL_METADATA"
  }
}

# ── Firewall — deny all by default ────────────────────────
resource "google_compute_firewall" "deny_all_ingress" {
  name      = "{{ name }}-deny-all-ingress"
  network   = google_compute_network.vpc.name
  direction = "INGRESS"
  priority  = 65534
  deny { protocol = "all" }
  source_ranges = ["0.0.0.0/0"]
}

resource "google_compute_firewall" "deny_all_egress" {
  name      = "{{ name }}-deny-all-egress"
  network   = google_compute_network.vpc.name
  direction = "EGRESS"
  priority  = 65534
  deny { protocol = "all" }
  destination_ranges = ["0.0.0.0/0"]
}

# ── Allow internal + Google APIs ──────────────────────────
resource "google_compute_firewall" "allow_internal" {
  name      = "{{ name }}-allow-internal"
  network   = google_compute_network.vpc.name
  direction = "INGRESS"
  priority  = 1000
  allow { protocol = "all" }
  source_ranges = [google_compute_subnetwork.private.ip_cidr_range]
}

{% if instance_count | default(0) > 0 %}
# ── Private Compute Instance ──────────────────────────────
resource "google_compute_instance" "private" {
  count        = {{ instance_count | default(1) }}
  name         = "{{ name }}-instance-${count.index}"
  machine_type = "{{ machine_type | default('e2-micro') }}"
  zone         = "{{ region }}-a"

  boot_disk {
    initialize_params {
      image  = "debian-cloud/debian-12"
      size   = {{ volume_size | default(20) }}
      type   = "pd-ssd"
    }
    kms_key_self_link = google_kms_crypto_key.disk_key.id
  }

  network_interface {
    subnetwork = google_compute_subnetwork.private.id
    # No access_config = no public IP assigned
  }

  shielded_instance_config {
    enable_secure_boot          = true
    enable_vtpm                 = true
    enable_integrity_monitoring = true
  }

  metadata = {
    enable-oslogin = "TRUE"
    block-project-ssh-keys = "true"
  }

  service_account {
    email  = google_service_account.vm_sa.email
    scopes = ["cloud-platform"]
  }
}

resource "google_service_account" "vm_sa" {
  account_id   = "{{ name }}-vm-sa"
  display_name = "{{ name }} VM Service Account (least privilege)"
}

# ── KMS for disk encryption ────────────────────────────────
resource "google_kms_key_ring" "main" {
  name     = "{{ name }}-keyring"
  location = "{{ region }}"
}

resource "google_kms_crypto_key" "disk_key" {
  name            = "{{ name }}-disk-key"
  key_ring        = google_kms_key_ring.main.id
  rotation_period = "7776000s"   # 90 days
}
{% endif %}

output "vpc_id"              { value = google_compute_network.vpc.id }
output "private_subnet_cidr" { value = google_compute_subnetwork.private.ip_cidr_range }
'''

AZURE_SECURE_VNET_TF = '''
# Generated by Local AI DevSecOps Agent — Azure Secure VNet
terraform {
  required_providers {
    azurerm = { source = "hashicorp/azurerm", version = "~> 3.0" }
  }
}

provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy    = false
      recover_soft_deleted_key_vaults = true
    }
  }
  # Credentials from env: AZURE_CLIENT_ID, AZURE_CLIENT_SECRET,
  # AZURE_TENANT_ID, AZURE_SUBSCRIPTION_ID
}

resource "azurerm_resource_group" "main" {
  name     = "{{ name }}-rg"
  location = "{{ region }}"
  tags = { ManagedBy = "devsecops-agent", Compliance = "{{ compliance | join('+') }}" }
}

# ── VNet ──────────────────────────────────────────────────
resource "azurerm_virtual_network" "main" {
  name                = "{{ name }}-vnet"
  address_space       = ["{{ cidr | default('10.0.0.0/16') }}"]
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  tags = { Name = "{{ name }}-vnet" }
}

# ── Private Subnet ────────────────────────────────────────
resource "azurerm_subnet" "private" {
  name                 = "{{ name }}-private"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["10.0.1.0/24"]
}

# ── NSG — deny all by default ─────────────────────────────
resource "azurerm_network_security_group" "private" {
  name                = "{{ name }}-nsg"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  security_rule {
    name                       = "DenyAllInbound"
    priority                   = 4096
    direction                  = "Inbound"
    access                     = "Deny"
    protocol                   = "*"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}

resource "azurerm_subnet_network_security_group_association" "private" {
  subnet_id                 = azurerm_subnet.private.id
  network_security_group_id = azurerm_network_security_group.private.id
}

{% if instance_count | default(0) > 0 %}
# ── Private VM ────────────────────────────────────────────
resource "azurerm_linux_virtual_machine" "private" {
  name                  = "{{ name }}-vm"
  resource_group_name   = azurerm_resource_group.main.name
  location              = azurerm_resource_group.main.location
  size                  = "{{ vm_size | default('Standard_B1s') }}"
  admin_username        = "azureuser"
  network_interface_ids = [azurerm_network_interface.private.id]
  disable_password_authentication = true

  admin_ssh_key {
    username   = "azureuser"
    public_key = file("~/.ssh/id_rsa.pub")
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Premium_LRS"
    disk_encryption_set_id = azurerm_disk_encryption_set.main.id
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts-gen2"
    version   = "latest"
  }

  identity {
    type = "SystemAssigned"   # Managed identity — no static credentials
  }
}

resource "azurerm_network_interface" "private" {
  name                = "{{ name }}-nic"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.private.id
    private_ip_address_allocation = "Dynamic"
    # No public_ip_address_id = private only
  }
}

resource "azurerm_disk_encryption_set" "main" {
  name                = "{{ name }}-des"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  key_vault_key_id    = azurerm_key_vault_key.disk.id

  identity { type = "SystemAssigned" }
}

resource "azurerm_key_vault_key" "disk" {
  name         = "{{ name }}-disk-key"
  key_vault_id = azurerm_key_vault.main.id
  key_type     = "RSA"
  key_size     = 4096
  key_opts     = ["decrypt","encrypt","sign","unwrapKey","verify","wrapKey"]
}
{% endif %}

# ── Key Vault ─────────────────────────────────────────────
data "azurerm_client_config" "current" {}

resource "azurerm_key_vault" "main" {
  name                        = "{{ name }}-kv"
  location                    = azurerm_resource_group.main.location
  resource_group_name         = azurerm_resource_group.main.name
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  sku_name                    = "premium"
  purge_protection_enabled    = true
  soft_delete_retention_days  = 90
  enable_rbac_authorization   = true
}

output "vnet_id"          { value = azurerm_virtual_network.main.id }
output "private_subnet_id" { value = azurerm_subnet.private.id }
output "key_vault_id"     { value = azurerm_key_vault.main.id }
'''

# ─── Data class for generation result ────────────────────────────────────────

@dataclass
class GenerationResult:
    success: bool
    files: List[str] = field(default_factory=list)
    output_dir: str = ""
    warnings: List[str] = field(default_factory=list)
    security_issues: List[dict] = field(default_factory=list)
    error: str = ""

# ─── Generator ────────────────────────────────────────────────────────────────

class IaCGenerator:
    TEMPLATE_MAP = {
        ("aws",   "terraform"): AWS_SECURE_VPC_TF,
        ("gcp",   "terraform"): GCP_SECURE_VPC_TF,
        ("azure", "terraform"): AZURE_SECURE_VNET_TF,
    }

    def __init__(self, output_base="./outputs"):
        self.output_base = output_base

    def generate(self, intent: dict, session) -> GenerationResult:
        """Generate IaC code for the given intent and session."""
        key = (session.cloud, session.iac_tool)
        template_str = self.TEMPLATE_MAP.get(key)

        if not template_str:
            return GenerationResult(False, error=f"No template for {key}")

        # Build template context
        ctx = self._build_context(intent, session)

        # Render template
        env = Environment(loader=BaseLoader(), autoescape=False,
                          trim_blocks=True, lstrip_blocks=True)
        template = env.from_string(template_str)
        rendered = template.render(**ctx)

        # Security guardrail check on generated code
        issues = self._check_guardrails(rendered)

        # Write output files
        run_id = hashlib.md5(json.dumps(ctx, default=str).encode()).hexdigest()[:8]
        out_dir = os.path.join(self.output_base, f"{session.cloud}_{run_id}")
        os.makedirs(out_dir, exist_ok=True)

        ext = "tf" if session.iac_tool == "terraform" else "py"
        main_file = os.path.join(out_dir, f"main.{ext}")
        with open(main_file, "w") as f:
            f.write(rendered)

        # Write versions/backend files for Terraform
        if session.iac_tool == "terraform":
            self._write_terraform_support_files(out_dir, session)

        files = [str(p) for p in Path(out_dir).glob(f"*.{ext}") if p.is_file()]
        files += [str(p) for p in Path(out_dir).glob("*.tf") if p.is_file()]
        files = list(set(files))

        return GenerationResult(
            success=True,
            files=files,
            output_dir=out_dir,
            security_issues=issues
        )

    def _build_context(self, intent: dict, session) -> dict:
        """Build Jinja2 template context from intent + session."""
        ctx = {
            "region":      session.region,
            "cloud":       session.cloud,
            "iac_tool":    session.iac_tool,
            "compliance":  session.compliance_targets or ["cis"],
            "name":        intent.get("name", "secure-infra"),
            "env":         intent.get("environment", "production"),
            "cidr":        intent.get("cidr", "10.0.0.0/16"),
            "az_count":    intent.get("az_count", 2),
            "instance_count": intent.get("instance_count", 1),
            "instance_type": intent.get("instance_type", "t3.micro"),
            "volume_size": intent.get("volume_size", 20),
            "machine_type": intent.get("machine_type", "e2-micro"),
            "vm_size":     intent.get("vm_size", "Standard_B1s"),
        }
        # GCP needs project_id
        if session.cloud == "gcp" and hasattr(session.credentials, "project_id"):
            ctx["project_id"] = session.credentials.project_id
        return ctx

    def _check_guardrails(self, code: str) -> List[dict]:
        """Scan generated code for security anti-patterns."""
        issues = []
        for pattern, severity, message in FORBIDDEN_PATTERNS:
            if re.search(pattern, code, re.IGNORECASE):
                issues.append({"severity": severity, "rule": pattern[:30], "description": message})
        return issues

    def _write_terraform_support_files(self, out_dir: str, session):
        """Write backend.tf and versions.tf."""
        backend = '''terraform {
  backend "local" {
    path = "terraform.tfstate"
    # For production: use encrypted remote backend
    # backend "s3" { bucket = "..." encrypt = true kms_key_id = "..." }
  }
}'''
        with open(os.path.join(out_dir, "backend.tf"), "w") as f:
            f.write(backend)

# ─── Intent parser (simple NLP without LLM — works offline) ──────────────────

class IntentParser:
    """
    Lightweight intent parser that works without a local LLM.
    When Ollama is available it uses the LLM; otherwise falls back to rules.
    """

    INSTANCE_TYPES_AWS = {
        "small": "t3.micro", "medium": "t3.small", "large": "t3.medium",
        "xlarge": "t3.large", "production": "t3.medium",
    }
    MACHINE_TYPES_GCP = {
        "small": "e2-micro", "medium": "e2-small", "large": "e2-medium",
        "xlarge": "n2-standard-2", "production": "e2-medium",
    }

    def parse(self, prompt: str, session) -> dict:
        """Parse prompt into a structured intent dict."""
        p = prompt.lower()
        intent = {
            "raw_prompt": prompt,
            "name": self._extract_name(p),
            "resource_types": self._extract_resources(p),
            "instance_count": self._extract_count(p),
            "instance_type": self._extract_instance_type(p, session.cloud),
            "az_count": 2 if "ha" in p or "high availability" in p else 1,
            "environment": self._extract_env(p),
            "cidr": self._extract_cidr(p),
            "volume_size": self._extract_storage(p),
            "security_features": self._extract_security(p),
        }
        return intent

    def _extract_name(self, p: str) -> str:
        for word in ["project", "app", "service", "stack"]:
            idx = p.find(word)
            if idx != -1:
                after = p[idx:idx+30].split()[1:3]
                if after:
                    return "-".join(after)[:20].replace(" ", "-")
        return "secure-infra"

    def _extract_resources(self, p: str) -> list:
        resources = []
        checks = [("vpc","vpc"),("subnet","subnet"),("instance","instance"),
                  ("ec2","instance"),("vm","instance"),("virtual machine","instance"),
                  ("database","rds"),("rds","rds"),("s3","s3"),("bucket","s3"),
                  ("eks","eks"),("kubernetes","kubernetes"),("k8s","kubernetes")]
        for kw, res in checks:
            if kw in p and res not in resources:
                resources.append(res)
        if not resources:
            resources = ["vpc", "instance"]
        return resources

    def _extract_count(self, p: str) -> int:
        import re
        m = re.search(r'(\d+)\s+(instance|server|vm|node|machine|ec2)', p)
        if m: return int(m.group(1))
        for word, num in [("one","1"),("two","2"),("three","3"),("single","1")]:
            if word in p: return int(num)
        return 1

    def _extract_instance_type(self, p: str, cloud: str) -> str:
        types_aws = self.INSTANCE_TYPES_AWS
        types_gcp = self.MACHINE_TYPES_GCP
        # Check if explicit instance type mentioned
        import re
        m = re.search(r'\b(t[23]\.\w+|m[45]\.\w+|c[56]\.\w+|e2-\w+|n[12]-\w+)\b', p)
        if m: return m.group(1)
        for size_word, val in types_aws.items():
            if size_word in p:
                return types_gcp.get(size_word, val) if cloud == "gcp" else val
        return "t3.micro" if cloud == "aws" else ("e2-micro" if cloud == "gcp" else "Standard_B1s")

    def _extract_env(self, p: str) -> str:
        for env in ["production", "prod", "staging", "dev", "development", "test"]:
            if env in p: return "production" if env == "prod" else env
        return "production"

    def _extract_cidr(self, p: str) -> str:
        import re
        m = re.search(r'\b(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/\d{1,2})\b', p)
        return m.group(1) if m else "10.0.0.0/16"

    def _extract_storage(self, p: str) -> int:
        import re
        m = re.search(r'(\d+)\s*gb', p)
        return int(m.group(1)) if m else 20

    def _extract_security(self, p: str) -> list:
        features = []
        kws = [("encrypt", "encryption"), ("private", "private_networking"),
               ("mfa", "mfa"), ("ssm", "ssm"), ("audit", "audit_logging"),
               ("monitor", "monitoring"), ("log", "logging")]
        for kw, feat in kws:
            if kw in p: features.append(feat)
        # Always include baseline security
        for f in ["encryption", "private_networking", "audit_logging"]:
            if f not in features: features.append(f)
        return features
